# Portable Template Stage 1
# - Remove BucketName from template
# - Use parameters to specify KeyPair for EC2
# - Use parameters to specify AMI ID for EC2

Parameters:
  KeyName: 
    Type: 'AWS::EC2::KeyPair::KeyName'
    Description: 'Specify Key Pair for EC2'

  AMIID:
    Type: 'String'
    Description: 'Specify AMI ID for EC2'

Resources:
  CatsBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      Tags:
      - Key: Project
        Value: ABCD

  EC2AppServer:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: 't3.micro'
      KeyName: !Ref 'KeyName'
      ImageId: !Ref 'AMIID'

      Tags:
        - Key: Project
          Value: ABCD
        - Key: Name
          Value: APP Server
