# Portable Template Stage 3
# - Remove BucketName from template
# - Use parameters to specify KeyPair for EC2
# - Get latest AMI ID from Public parameters of SSM Parameter Store
#   More info: https://docs.aws.amazon.com/systems-manager/latest/userguide/parameter-store-public-parameters-ami.html
# - Working with Conditions
#   * Different syntax to use !Equals

Parameters:
  KeyName: 
    Type: 'AWS::EC2::KeyPair::KeyName'
    Description: 'Specify Key Pair for EC2'

  LatestAmiId:
    Description: "AMI for EC2"
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2'

  EnvName:
    Type: 'String'
    Description: 'Environment name'
    AllowedValues:
    - dev
    - uat
    - prod

Conditions:
  StackIsProd: !Equals [!Ref EnvName, 'prod']
  StackIsDev: !Equals
    - !Ref EnvName
    - 'dev'

Resources:
  CatsBucketDev:
    Type: 'AWS::S3::Bucket'
    Condition: StackIsDev
    Properties:
      Tags:
      - Key: Project
        Value: ABCD
      - Key: Env
        Value: !Ref EnvName

  CatsBucket:
    Type: 'AWS::S3::Bucket'
    Condition: StackIsProd
    Properties:
      Tags:
      - Key: Project
        Value: ABCD
      - Key: Env
        Value: !Ref EnvName

  EC2AppServer:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: 't3.micro'
      KeyName: !Ref 'KeyName'
      ImageId: !Ref 'LatestAmiId'

      Tags:
        - Key: Project
          Value: ABCD
        - Key: Name
          Value: !Join ['-', ['APP Server', !Ref EnvName]]
        - Key: Env
          Value: !Ref EnvName
